[project]
name = "ocr-api"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "redis",         # Para conectar con Redis
  "python-multipart", # Para subir archivos
]
